@startuml

[*] --> A

state "Приём и обработка заказа" as PreOrder #pink {
    A -down-> B
    B -up[#green]-> B : Retry 
    B --> C: Платёж\nсоздан 
    C -up-> C : Retry 
    C -[#FF8888]-> D : Пришло\nподтверждение\nплатежа  
    D -up[#8888FF]-> D : Retry 
    C -> outReturnStore : Подтверждение\nплатежа\nне пришло
    B -> outReturnStore : Платёж не\nбыл создан

    state outReturnStore <<exitPoint>>
    state C #magenta
}

D --> I : Не удалось\nскомплектовать\nзаказ
outReturnStore --> M


state "Доставка" as Delivering {
    D --> inOrderProcessing : Успешная комплектация заказа

    inOrderProcessing --> E 
    E -up-> E :  Retry 
    E --> F
    F --> G
    F --> H
    H --> outOrderProcessingReturn
    G --> outOrderProcessingDone
    
    state "Вход" as inOrderProcessing <<entryPoint>> 
    state "Возврат\nтовара" as outOrderProcessingReturn <<exitPoint>>
    state "Исполнение\nзаказа" as outOrderProcessingDone <<exitPoint>>

    state E #lightblue
}



state "Возврат платежа" as PAymentReversing {
    outOrderProcessingReturn -down-> K
    I --> K 
    K -up-> K : Retry 

    K --> J
    J -up-> J : Retry 

    J --> L
}

L --> M
M --> N
A --> N
outOrderProcessingDone -down-> O

O --> [*]
N --> [*]

A : Заказ создан
B : Товаp\nзарезервирован
C : Платёж создан
D : Оплачено 
E : Заказ\nскомплектован
F : Заказ\nпередан\nкурьеру
G : Доставка\nподтверждена
H : Товар\nвозвращён\nв магазин
I : Заказ не\nскомплектован 
J : Возврат\nплатежа\nсоздан
K : Готовится\nвозврат платежа
L : Платёж\nвозвращен
M : Резерв\nвозращен\nна склад
N : Заказ\nотменён
O : Заказ\nисполнен

state I #red
@enduml